LIPO_WIDTH = 36.6;

LIPO_BODY_HEIGHT = 52.4;
LIPO_BODY_DEPTH = 10.3;

LIPO_TOP_HEIGHT = 14;
LIPO_TOP_DEPTH = 11;

module lipo_cell() {
    cube([LIPO_WIDTH, LIPO_BODY_DEPTH, LIPO_BODY_HEIGHT]);
    translate([0, -(LIPO_TOP_DEPTH / LIPO_BODY_DEPTH) / 2, LIPO_BODY_HEIGHT])
    cube([LIPO_WIDTH, LIPO_TOP_DEPTH, LIPO_TOP_HEIGHT]);
}

//lipo_cell();
